use_frameworks!

platform :ios, '9.0'

target 'FMBaseiOSKit_Example' do
  pod 'FMBaseiOSKit', :path => '../'
  pod 'FMPickerView'
  target 'FMBaseiOSKit_Tests' do
    inherit! :search_paths

    
  end
end
