source 'https://gitee.com/Coder_FM/FMPodSpec.git'
use_frameworks!

platform :ios, '8.0'

target 'FMBaseiOSKit_Example' do
  pod 'FMBaseiOSKit', :path => '../'

  target 'FMBaseiOSKit_Tests' do
    inherit! :search_paths

    
  end
end
